// DAX Query
DEFINE
	VAR __DS0FilterTable = 
		TREATAS({"NIGHTLY"}, 'Plan Versions'[Plan Version])

	VAR __DS0FilterTable2 = 
		TREATAS({@plan_versions}, 'Plan Versions'[Plan Name])

	VAR __DS0FilterTable3 = 
		TREATAS({-1,
			0,
			1,
			2,
			3,
			4,
			5,
			6,
			BLANK()}, 'Dates'[Current Month Offset])

	VAR __DS0FilterTable4 = 
		FILTER(
			KEEPFILTERS(VALUES('Products'[Is Licensed])),
			AND('Products'[Is Licensed] IN {"N"}, NOT('Products'[Is Licensed] IN {BLANK()}))
		)

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			'Dates'[Year/Period/Month],
			__DS0FilterTable,
			__DS0FilterTable2,
			__DS0FilterTable3,
			__DS0FilterTable4,
			"Constrained_Receipt_Plan_Units", 'Inventory Plans'[Constrained Receipt Plan Units],
			"Total_Receipt_Plan_Units", 'Inventory Plans'[Total Receipt Plan Units],
			"Planned_Production_Units", 'Inventory Plans'[Planned Production Units],
			"Work_In_Progress_Units", 'Inventory Plans'[Work In Progress Units],
			"In_Transit_Units", 'Inventory Plans'[In Transit Units],
			"Sales_Demand_Units", 'Inventory Plans'[Sales Demand Units]
		)

	

EVALUATE
	__DS0Core


