// DAX Query
DEFINE
	MEASURE '#Local Measures'[SlicerCheck] = 
		(/* USER DAX BEGIN */

CALCULATE ( IF ( ISFILTERED ( 'Plan Versions'[Plan Name] ), 1, 0 ), ALLSELECTED ( 'Plan Versions' ) )
/* USER DAX END */)

	VAR __DS0FilterTable = 
		TREATAS({@inventory_plans_start_month}, 'Inventory Plans Start Month'[Start Fiscal Year/Month])

	VAR __DS0FilterTable2 = 
		TREATAS({@inventory_plans_end_month}, 'Inventory Plans End Month'[End Fiscal Year/Month])

	VAR __DS0FilterTable3 = 
		TREATAS({"NIGHTLY"}, 'Plan Versions'[Plan Version])

	VAR __DS0FilterTable4 = 
		TREATAS({@plan_versions}, 'Plan Versions'[Plan Name])

	VAR __DS0FilterTable5 = 
		FILTER(
			KEEPFILTERS(VALUES('Products'[Is Licensed])),
			AND('Products'[Is Licensed] IN {"N"}, NOT('Products'[Is Licensed] IN {BLANK()}))
		)

	VAR __DS0FilterTable6 = 
		TREATAS({"Inv Dem"}, 'Reporting Notification Messages'[Content ID])

	VAR __ValueFilterDM0 = 
		FILTER(
			KEEPFILTERS(
				SUMMARIZECOLUMNS(
					'Dates'[Year/Period/Month],
					'Dates'[Current Month Offset],
					__DS0FilterTable,
					__DS0FilterTable2,
					__DS0FilterTable3,
					__DS0FilterTable4,
					__DS0FilterTable5,
					__DS0FilterTable6,
					"Sales_Demand_Units", 'Inventory Plans'[Sales Demand Units],
					"Constrained_Receipt_Plan_Units", 'Inventory Plans'[Constrained Receipt Plan Units],
					"Total_Receipt_Plan_Units", 'Inventory Plans'[Total Receipt Plan Units],
					"Forward_Weeks_Of_Coverage", 'Inventory Plans'[Forward Weeks Of Coverage],
					"Planned_Production_Units", 'Inventory Plans'[Planned Production Units],
					"Work_In_Progress_Units", 'Inventory Plans'[Work In Progress Units],
					"In_Transit_Units", 'Inventory Plans'[In Transit Units],
					"SlicerCheck", IGNORE('#Local Measures'[SlicerCheck])
				)
			),
			[SlicerCheck] = 1
		)

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			'Dates'[Year/Period/Month],
			'Dates'[Current Month Offset],
			__DS0FilterTable,
			__DS0FilterTable2,
			__DS0FilterTable3,
			__DS0FilterTable4,
			__DS0FilterTable5,
			__DS0FilterTable6,
			__ValueFilterDM0,
			"SalesDemandUnits", 'Inventory Plans'[Sales Demand Units],
			"ConstrainedReceiptPlanUnits", 'Inventory Plans'[Constrained Receipt Plan Units],
			"TotalReceiptPlanUnits", 'Inventory Plans'[Total Receipt Plan Units],
			"ForwardWeeksOfCoverage", 'Inventory Plans'[Forward Weeks Of Coverage],
			"PlannedProductionUnits", 'Inventory Plans'[Planned Production Units],
			"WorkInProgressUnits", 'Inventory Plans'[Work In Progress Units],
			"InTransitUnits", 'Inventory Plans'[In Transit Units]
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(501, __DS0Core, 'Dates'[Current Month Offset], 1, 'Dates'[Year/Period/Month], 1)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	'Dates'[Current Month Offset], 'Dates'[Year/Period/Month]
